services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: