services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    networks:
      - app-networks

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    networks:
      - app-networks

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - app-networks
    depends_on:
      - database
    
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-networks

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge

volumes:
  db-data: